<a href="https://colab.research.google.com/github/Gh6if84vi/DataScience-Learning-/blob/main/Numpy_part_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#creating numpy arrays
import numpy as np
#1-D array
a=np.array([12,23,4,5,67,78,121])
a

array([ 12,  23,   4,   5,  67,  78, 121])

In [2]:
#2D array
b=np.array([[1,2,3,4,],[5,6,7,78]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7 78]]


In [3]:
#3D array
c=np.array([[[1,2,3,4],[3,4,5,6]],[[5,6,7,7],[7,8,9,9]]])
c

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[5, 6, 7, 7],
        [7, 8, 9, 9]]])

In [4]:
#Datatype of an array
np.array([1,-2,3,4,0],dtype=bytes)


array([b'1', b'-2', b'3', b'4', b'0'], dtype='|S2')

In [5]:
#shape of an array
c.shape

(2, 2, 4)

In [6]:
#size of an array
c.size

16

In [7]:
#no.of dimensions in an array
c.ndim

3

In [8]:
#np.arange
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [9]:
#reshape
np.arange(12,32).reshape(4,5)

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31]])

In [10]:
#np.ones and np.zeros
e=np.ones((3,4))
print(e)
f=np.zeros((4,5))
print(f)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#np.random
r=np.random.random((3,4))
print(r)

[[0.09484527 0.51659428 0.24074154 0.22556793]
 [0.1930453  0.46114445 0.64190779 0.543445  ]
 [0.74324801 0.58815081 0.01415755 0.47440616]]


In [12]:
#np.linspace
#syntax=np.linspace(range,no.of digits)
l=np.linspace(-10,10,10)
l

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
#to create an array with 5 dimensions
arr=np.array([1,2,3,4],ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [14]:
#np.identity
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#Array Attributes

In [15]:
#np.ndim
#np.shape
#np.size


In [16]:
#np.itemsize
item=np.array([1,2,3,4,5,5],dtype=int)
print(item.itemsize)

8


# **Changing DataType**

In [17]:
age=np.array([23,24,21,34,45,67])
age.dtype
age.astype(np.int32)

array([23, 24, 21, 34, 45, 67], dtype=int32)

# **Array Operations**

In [18]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
#arithmetic
a1*5

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [20]:
a2>=15

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
#vector operations
print(a1+a2)
print(a1*a2)
print(a1%a2)
print(a1/a2)
print(a1-a2)
print(a1^a2)
print(a1**a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[12 12 12 12]
 [20 20 20 20]
 [28 28 28 28]]
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


# *Array  Functions**

In [22]:
f1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [23]:
#max/min/sum/prod
np.max(a1,axis=1)

array([ 300,  700, 1100])

In [24]:
np.prod(a1,axis=0)

array([        0,  45000000, 120000000, 231000000])

In [25]:
np.sum(a1,axis=1)
print(np.sum(a1,axis=0))

[1200 1500 1800 2100]


In [26]:
#mean
np.mean(a1,axis=1)

array([150., 550., 950.])

In [27]:
#median
np.median(a1,axis=1)

array([150., 550., 950.])

In [28]:
#dot product
a3=np.array([1,2,3,4])
a4=np.array([4,5,6,7],dtype=float)
np.dot(a3,a4)

60.0

In [29]:
#standard deviation
np.std(a1)

345.2052529534663

In [30]:
#variance
np.var(a1)

119166.66666666667

In [31]:
#sine,cosine,tan
print(np.sin(a3))
print(np.cos(a3))
print(np.tan(a3))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [32]:
#log and exponents
print(np.log(a4))
print(np.exp(a4))

[1.38629436 1.60943791 1.79175947 1.94591015]
[  54.59815003  148.4131591   403.42879349 1096.63315843]


In [33]:
#round/ceil/floor
a5=np.random.random((4,5))*100
print(f"a5 matrix is :\n{a5}")
print(f"round matrix is :\n{np.round(a5)}")
print(f"ceil matrix is :\n{np.ceil(a5)}")
print(f"floor matrix is :\n{np.floor(a5)}")

a5 matrix is :
[[88.40220154 69.35028786 97.29435273 52.25375435 51.26632539]
 [34.9666185   1.85230836 84.18559823 26.19639206 58.33251063]
 [48.20035053 46.19563524 48.84761181 38.84719863 12.04290775]
 [59.52295907 25.34074102 16.71689109 10.55214186 12.57526615]]
round matrix is :
[[88. 69. 97. 52. 51.]
 [35.  2. 84. 26. 58.]
 [48. 46. 49. 39. 12.]
 [60. 25. 17. 11. 13.]]
ceil matrix is :
[[89. 70. 98. 53. 52.]
 [35.  2. 85. 27. 59.]
 [49. 47. 49. 39. 13.]
 [60. 26. 17. 11. 13.]]
floor matrix is :
[[88. 69. 97. 52. 51.]
 [34.  1. 84. 26. 58.]
 [48. 46. 48. 38. 12.]
 [59. 25. 16. 10. 12.]]


# **Indexing and Slicing**

In [34]:
c1=np.arange(16)
c2=np.arange(12).reshape(3,4)
c3=np.arange(8).reshape(2,2,2)
print(f"c1 is :\n{c1}")
print(f"c2 is :\n{c2}")
print(f"c3 is :\n{c3}")

c1 is :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
c2 is :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c3 is :
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [35]:
#for 1-D
print(c1[-1])
print(c1[0])

15
0


In [36]:
#For 2D
print(c2[1][2])
print(c2[1])
print(c2[-1][1])

6
[4 5 6 7]
9


In [37]:
#For 3D
print(c3)
print("-------------")
print(c3[1][0][1])
print(c3[1,0,1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
-------------
5
5


In [38]:
#slicing
print(c1[2:5])

[2 3 4]


In [44]:
print(c2[:3,0])
print(c2[:,:])
print(c2[:,-1])
print(c2[1:3,1:3])
print(c2[::2,::3])
print(c2[1,::3])
print(c2[0:2,1:4])

[0 4 8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 3  7 11]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [47]:
q=np.arange(27).reshape(3,3,3)
q


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [56]:
print(q[1])
print(q[::2])
print(q[0,1,:3])
print(q[1,:,1])
print(q[2,1:,1:])
print(q[::2,0,::2])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


#Iterating

In [58]:
print(c1)
print(c2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [59]:
for i in np.nditer(c2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [61]:
#3D array
for i in np.nditer(q):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# **Reshaping**

In [65]:
#reshape
r=np.arange(12).reshape(2,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [66]:
#transpose
r.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [67]:
q1=q.ravel()
q1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

**Stacking**

In [70]:
#horizontally
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)
print(b1)
print(b2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [73]:
print(np.hstack((b1,b2,b1,b2)))

[[ 0  1  2  3 12 13 14 15  0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19  4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23  8  9 10 11 20 21 22 23]]


In [77]:
#vertical stacking
print(np.vstack((b1,b2)))
print("---------------------")
print(np.vstack((b1,b2,b1+b2,b2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
---------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [78]:
print(np.vstack((b1*2,b1*b2,b2*2)))

[[  0   2   4   6]
 [  8  10  12  14]
 [ 16  18  20  22]
 [  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]
 [ 24  26  28  30]
 [ 32  34  36  38]
 [ 40  42  44  46]]


# **Splitting**

In [80]:
#horizontal splitting
print(np.hsplit(b2,4))

[array([[12],
       [16],
       [20]]), array([[13],
       [17],
       [21]]), array([[14],
       [18],
       [22]]), array([[15],
       [19],
       [23]])]


In [84]:
np.hsplit(b2,2)

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [87]:
#vertical splitting
print(b2)
print(np.vsplit(b2,3))

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
